# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Porta.jl
email: mjazadi42@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Mathematical objects inspire us to build computer generated images, some of which you can
  view on the YouTube channel. Much like how people go on a trip to explore nature in the
  physical world, we go on many adventures, starting from the mental world into the platonic
  mathematical world. We also like to take a digital camera with us for recording parts of
  our memorable experiences. The kind of experiences that will help introduce a
  transcendental view of reality for the purpose of shaping the future culture.
baseurl: "/Porta.jl" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iamazadi
github_username:  iamazadi

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
